# Meta Data for SEO

## Homepage
title = "Green Metrics Tool"
titleSeparator = "-"
titleAddition = "Green Metrics Tool"
description = "Description"

## Documentation
# docsVersion = "0.3"

## Open Graph
#images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "docs.green-coding.io"
titleHome = "Green Metrics Tool Documentation"

## Twitter Cards
#twitterSite = "@getdoks"
#twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
#schemaType = "Organization"
#schemaName = "Doks"
#schemaAuthor = "Henk Verlinde"
#schemaAuthorTwitter = "https://twitter.com/henkverlinde"
#schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
#schemaAuthorGitHub = "https://github.com/h-enk"
#schemaLocale = "en-US"
#schemaLogo = "logo-doks.png"
#schemaLogoWidth = 512
#schemaLogoHeight = 512
#schemaImage = "doks.png"
#schemaImageWidth = 1280
#schemaImageHeight = 640
#schemaTwitter = "https://twitter.com/getdoks"
#schemaLinkedIn = ""
#schemaGitHub = "https://github.com/h-enk/doks"
#schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.cloudlare.com/\">Cloudflare</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) Green Coding Solutions"

# Alert
alert = false
alertDismissable = true

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/green-coding-solutions/documentation"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

mainSections = ["docs"]

# Doks configuration for thulite/doks v1
[doks]
  # Color mode
  colorMode = "auto"  # auto (default), light or dark
  colorModeToggler = true  # true (default) or false
  
  # Navbar
  navbarSticky = true
  containerBreakpoint = "lg"
  
  # Search
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  # Search results
  showDate = false # false (default) or true
  showSummary = true # true (default) or false
  searchLimit = 10 # 0 (no limit, default) or natural number
  
  # Bootstrap
  bootstrapJavascript = true # false (default)
  
  # Navigation
  sectionNav = ["docs"]
  toTopButton = false
  breadcrumbTrail = false
  headlineHash = true
  scrollSpy = true

  # Alerts
  alert = false

  # [doks.menu]
  #   [doks.menu.section]
  #     auto = true
  #     collapsibleSidebar = true
  
# Debug
[render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error (fails the build)
highlightBroken = true # true or false (default)

# TODO: Cleanup
# [options]
#   clipBoard = true
#   instantPage = true
#   highLight = true
#   kaTex = false
#   docsVersioning = false
#   fullWidth = false
