## Hugo
title = "Green Metrics Tool"
titleSeparator = "-"
titleAddition = "Green Metrics Tool"
description = "Documentation of the Green Metrics Tool"

mainSections = ["docs"]

## Open Graph
#images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "docs.green-coding.io"
titleHome = "Green Metrics Tool Documentation"

## Twitter Cards
#twitterSite = "@getdoks"
#twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
#schemaType = "Organization"
#schemaName = "Doks"
#schemaAuthor = "Henk Verlinde"
#schemaAuthorTwitter = "https://twitter.com/henkverlinde"
#schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
#schemaAuthorGitHub = "https://github.com/h-enk"
#schemaLocale = "en-US"
#schemaLogo = "logo-doks.png"
#schemaLogoWidth = 512
#schemaLogoHeight = 512
#schemaImage = "doks.png"
#schemaImageWidth = 1280
#schemaImageHeight = 640
#schemaTwitter = "https://twitter.com/getdoks"
#schemaLinkedIn = ""
#schemaGitHub = "https://github.com/h-enk/doks"
#schemaSection = "blog"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.cloudlare.com/\">Cloudflare</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Doks configuration for thulite/doks v1
[doks]
  # Color mode
  colorMode = "auto"  # auto (default), light or dark
  colorModeToggler = true  # true (default) or false
  
  # Navbar
  navbarSticky = true
  containerBreakpoint = "lg"
  
  # Search
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  # Search results
  showDate = false
  showSummary = true
  searchLimit = 10 # 0 (no limit, default)
  
  # Global alert
  alert = false
  alertDismissable = true

  # Bootstrap
  bootstrapJavascript = true # false (default)
  
  # Navigation
  sectionNav = ["docs"]
  toTopButton = false
  breadcrumbTrail = false
  headlineHash = true
  scrollSpy = true

  # Multilingual
  multilingualMode = false

  # Versioning
  docsVersioning = false

  # Repository
  editPage = false
  lastMod = false
  repoHost = "GitHub"
  docsRepo = "https://github.com/h-enk/doks"
  docsRepoBranch = "main"
  docsRepoSubPath = ""
