---
name: HUGO energy cost
author: Arne Tarara
description: Measure energy cost of HUGO build for documentation
architecture: linux

services:
  hugo-container:
    image: klakegg/hugo:0.101.0-alpine
    commmand: shell
    setup-commands:
      - cp -R /tmp/repo /src

flow:
  - name: Build Hugo
    container: hugo-container
    commands:
      - type: console
        command: hugo -s /src/repo
        note: Starting HUGO build